### ISSUE TITLE
Forgot two sentences

### ISSUE THREAD

**Issue by chepioq** [Musikolo/plasma5-applets-system-panel#1]
Hi Musikolo
I test your develop branch, and that work for me.
But you have forgotten two sentences to translate: 
In ConfigLayout.qml you have : 

```
    QtControls.RadioButton {
        id: changeIconsAction
        anchors.left: parent.left
        anchors.leftMargin: 10
        text: "Change icons"
        checked: true
        exclusiveGroup: actionRadioGroup
        onClicked: uncheckToolButtons()
    }
    QtControls.RadioButton {
        id: rearrangeIconsAction
        anchors.left: parent.left
        anchors.leftMargin: 10
        text: "Rearrange icons"
        exclusiveGroup: actionRadioGroup
    }
```

But for translate you must have : 

```
    QtControls.RadioButton {
        id: changeIconsAction
        anchors.left: parent.left
        anchors.leftMargin: 10
        text: i18n("Change icons")
        checked: true
        exclusiveGroup: actionRadioGroup
        onClicked: uncheckToolButtons()
    }
    QtControls.RadioButton {
        id: rearrangeIconsAction
        anchors.left: parent.left
        anchors.leftMargin: 10
        text: i18n("Rearrange icons")
        exclusiveGroup: actionRadioGroup
    }
```

If that help you.

**Comment by Musikolo** [comment]
Hi Chepioq,

I'm currently getting close the final changes I want to include for the next release. Yesterday, I got a lot of progress, so the release day is real close. At this time, I'm not paying attention to the translations because I need to get the work of the release done and validate everything works seamlessly. After that, I'll update the translation files and I'll send you another message to request your help to get the French translation updated.

Once again, I really appreciate your interest and big contributions you're doing in this project.

Thank you!

**Comment by chepioq** [comment]
Ok
Yesterday  I just test the guy, and it's good.
But the new features don't work, I can't click on apply button, it's grey and don't work.

I like your applet and use it every days.

If you want I test for you, no problem.

**Comment by chepioq** [comment]
Hi Muzikolo
I test your last commit, that work for Rearrange icons, but that don't work for changing icon.
I change icon for other on my laptop, but nothing appear, the old icon is replace by a blank one.

Fortunately the reset button work fine.

**Comment by Musikolo** [comment]
Hi Chepioq,

I run into more issues than expected, particularly with the piece for changing icons. This piece is not 100% complete and it will only work if you choose system icons like the ones you find in `/usr/share/icons` directly. Every other icon will not work, as you already noticed. The reason for that is that the way it's implemented now, I'm passing just the name of icon file, not the full path and extension. KDE takes care of choosing an icon that matches up with this name and best suits for the size requirements where it needs to be displayed. This is preferred in most cases because the quality of the icon is always optimized. However, I thought about the need of providing the user with a way to disable this feature and enforce the absolute path to the icon to be used. This is something I want to do. I have a few ideas on top of my head, and I hope to get it implemented shortly.

I'm happy every else looks good to you. I appreciate your feedback, as usual! ;-)

Thank you!

**Comment by Musikolo** [comment]
Hi Chepioq,

I've done quite a few changes and I think I got the code fairly stable now. I'm now focusing my efforts in making sure the code is working smoothly. Then, I'll push another update with the translation files, so that you can update the French one.

Please, feel free to try it out and share your feedback.

Thank you!

**Comment by chepioq** [comment]
Hi Musikolo
I test the new version and for me that work fine.
It's a good idea to separate icons setting in two way : icons system and icons user.
With icons system that all work.
With icons user, some icons don't work and are blank.

For translation, I apply extract-and-merge-messages.sh in translation folder, and I translate fr.po.
It's here : http://sd-1.archive-host.com/membres/up/138795649635992281/frpo.zip

**Comment by Musikolo** [comment]
Hi Chepioq,

I've pushed a number of changes including your translation file, small improvements and some code cleanups. This should be the final code for version 1.3.0. Please, feel free to test it out and let me know, if you find anything that doesn't work as expected.

Once again, thanks a lot your contribution and support!!

**Comment by chepioq** [comment]
Hi Musikolo
I test your last commit, and for me all work fine.
Thank for your great work.

**Comment by Musikolo** [comment]
Version 1.3.0, released.

Closing this issue...
